apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: global
  namespace: rhacm-policies
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
